version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_CREATE_TOPICS: "numtest:1:1"

  crud_service:
    build:
      context: .
      dockerfile: dockerfiles/crud.Dockerfile
    ports:
      - "5000:5000"
