apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crud
  template:
    metadata:
      labels:
        app: crud
    spec:
      containers:
        - name: crud
          image: gcr.io/superbrain-282909/crud:latest
          ports:
            - containerPort: 5000
      imagePullSecrets:
        - name: superbrainkey
---
apiVersion: v1
kind: Service
metadata:
  name: crud
spec:
  type: ClusterIP
  selector:
    app: crud
  ports:
  - name: http
    port: 5000
    targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: crud-external
spec:
  type: LoadBalancer
  selector:
    app: crud
  ports:
  - name: http
    port: 5000
    targetPort: 5000