apiVersion: apps/v1
kind: Deployment
metadata:
  name: timeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: timeline
  template:
    metadata:
      labels:
        app: timeline
    spec:
      containers:
        - name: timeline
          image: gcr.io/superbrain-282909/timeline:latest
          ports:
            - containerPort: 5000
      imagePullSecrets:
        - name: superbrainkey
---
apiVersion: v1
kind: Service
metadata:
  name: timeline
spec:
  type: ClusterIP
  selector:
    app: timeline
  ports:
  - name: http
    port: 5000
    targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: timeline-external
spec:
  type: LoadBalancer
  selector:
    app: timeline
  ports:
  - name: http
    port: 5000
    targetPort: 5000